name: Push language server proxy to DockerHub

on:
  push:
    branches:
      - "master"
    paths:
      - "proxy/**"
      - "proxy.Dockerfile"

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.5

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: exercism/language-server-proxy
          tag_with_sha: true
          tags: latest
          dockerfile: proxy.Dockerfile
